Introducción a TensorFlow 
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/neural-networks/tree/master/) para acceder al repositorio online.

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/neural-networks/tree/master/) para explorar el repositorio usando `nbviewer`. 

---

### Operaciones matemáticas básicas

In [18]:
import tensorflow as tf
import numpy as np

En el siguiente ejemplo se evaluará la epresión 5 * 3 - (3 + 2). Esta expresión puede ser representada a través del siguiente árbol sintáctico:

     [-]
      +--- [*]
      |     +---- [5]
      |     +---- [2]
      |
      +--- [+]
            +---- [3]
            +---- [2]

Note que en esta expresión el nodo con la constante 2 es común a ambas ramas y podría representarse de forma optimizada como:

     [-]
      +--- [*]
      |     +---- [5]
      |     +-----------+
      |                 |
      +--- [+]         [2] 
            +---- [3]   |
            +-----------+ 

Para realziar la evaluación usando `TensorFlow`, se debe construir explícitamente el grafo, para lo cual se enumeran los nodos de la siguiente forma:

     [-] (node6)
      +--- [*] (node4)
      |     +---- [5] (node1)
      |     +---------------------+
      |                           |
      +--- [+] (node5)           [2] (node2)
            +---- [3] (node3)     |
            +---------------------+ 


In [58]:
node1 = tf.constant(5.0)  
node2 = tf.constant(2.0)  
node3 = tf.constant(3.0)  
node4 = tf.multiply(node1, node2)
node5 = tf.add(node3, node2)
node6 = tf.subtract(node4, node5)

In [70]:
## el grafo puede accederse asi:
tf.get_default_graph()

In [73]:
## Para computar el resultado en un nodo se puede usar eval()
print('node6 = {}'.format(node6.eval()))
print('node4 = {}'.format(node4.eval()))

node6 = 5.0
node4 = 10.0


Para ejecutar una secuencia compleja de cálculos, se utiliza comunmente el abrir una sesión y ejecutar los calculos.

In [62]:
sess = tf.Session()             ## abre la sesion (en IPython use tf.InteractiveSession())
outs = sess.run(node6)          ## evalua el grafo y almacena el resultado
sess.close()                    ## cierra la sesión
print("outs = {}".format(outs)) ## imprime el resultado de la evaluación

outs = 5.0


Es mucho más comun usar el siguiente patrón de código en vez del anterior:

In [69]:
## Alternativa 1: usa run()
with tf.Session() as sess:
    outs = sess.run(node6)
    print("outs = {}".format(outs))

outs = 5.0


In [74]:
## run() admite una lista de nodos a evaluar
with tf.Session() as sess:
    outs = sess.run([node6, node4, node5])
    print("outs = {}".format(outs))

outs = [5.0, 10.0, 5.0]


A continuación se resumen las operaciones mas comunes (la lista completa de operadores puede ser consultada en https://www.tensorflow.org/api_guides/python/math_ops)

    Operacion               equivalente
    --------------------------------------
    tf.add(a, b)            a + b
    tf.multiply(a, b)       a * b
    tf.subtract(a, b)       a - b
    tf.divide(a, b)         a / b
    tf.pow(a, b)            a ** b
    tf.mod(a, b)            a % b
    
    tf.abs(a)               abs(a)
    tf.square(a)            a ** 2
    tf.sqrt(a)              sqrt(a)
    tf.exp(a)               exp(a)
    tf.negative(a)          -a
    tf.sigmoid(a)           1 / (1 + exp(-a))
    tf.sign                 sign(a)
    tf.maximum
    tf.minimum
    
    tf.logical_and(a, b)    a & b
    tf.logical_or(a, b)     a | b   
    tf.greater(a, b)        a > b
    tf.greater_equal(a, b)  a >= b
    tf.less_equal(a, b)     a <= b
    tf.less(a, b)           a < b
    tf.logical_not(a)       ~a 
    tf.equal(a, b)          a == b
    tf.not_equal            a != b
    


---
**Ejercicio.--** Compute $5*2^2 + 3 * 5 - 18$ usando TensorFlow.

---

### Matrices

In [114]:
a = np.ones((3,3))
b = tf.convert_to_tensor(a)
with tf.Session() as sess:
    print(sess.run(b))

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [75]:
tf.zeros((2,2)).eval()

array([[0., 0.],
       [0., 0.]], dtype=float32)

In [77]:
tf.ones((2,2)).eval()

array([[1., 1.],
       [1., 1.]], dtype=float32)

In [239]:
tf.random_normal((3,2),     ## shape
                 0,         ## mean
                 1).eval()  ## sd

array([[-1.2534955 ,  2.708091  ],
       [-0.5917414 ,  1.272865  ],
       [ 0.4079103 , -0.69752485]], dtype=float32)

In [238]:
tf.truncated_normal((3,2),     ## shape / muestrea los valores entre 2 ds de la media
                    0,         ## mean
                    1).eval()  ## sd

array([[ 1.3413297, -1.679636 ],
       [-1.2278032, -1.3790988],
       [ 0.7863774,  1.4791218]], dtype=float32)

In [90]:
tf.random_uniform((3,2),     ## shape
                  0,         ## minval
                  1).eval()  ## maxval

array([[0.16373658, 0.04911637],
       [0.62193847, 0.7107215 ],
       [0.85362566, 0.36942673]], dtype=float32)

In [91]:
tf.fill((3,2),      ## shape
        4).eval()   ## value

array([[4, 4],
       [4, 4],
       [4, 4]], dtype=int32)

In [96]:
tf.linspace(0.0, 1.0, 11).eval()

array([0.        , 0.1       , 0.2       , 0.3       , 0.4       ,
       0.5       , 0.6       , 0.7       , 0.8       , 0.90000004,
       1.        ], dtype=float32)

In [240]:
tf.constant([[1,2,3], 
             [4,5,6]]).eval()

array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)

In [246]:
tf.random_shuffle(tf.constant([1,2,3,4,5,6])).eval()

array([1, 6, 4, 3, 5, 2], dtype=int32)

In [83]:
## suma de las columnas
tf.reduce_sum(m, reduction_indices = 0).eval()

array([5, 7, 9], dtype=int32)

In [85]:
## suma de las filas
tf.reduce_sum(m, reduction_indices = 1).eval()

array([ 6, 15], dtype=int32)

In [101]:
## suma de todos los elementos
tf.reduce_sum(m).eval()

21

`TensorFlow` implementa las siguiente funciones para reducir un tensor (https://www.tensorflow.org/api_guides/python/math_ops#Reduction)

    tf.reduce_sum
    tf.reduce_prod
    tf.reduce_min
    tf.reduce_max
    tf.reduce_mean
    tf.reduce_all
    tf.reduce_any
    tf.reduce_logsumexp
    tf.count_nonzero
    tf.accumulate_n
    tf.einsum
    

In [243]:
## dimensiones
m = tf.constant([[1,2,3], 
                 [4,5,6]])
m.get_shape()

TensorShape([Dimension(2), Dimension(3)])

In [244]:
a = m + m
a.eval()

array([[ 2,  4,  6],
       [ 8, 10, 12]], dtype=int32)

In [98]:
tf.reshape(m,(1,6)).eval()

array([[1, 2, 3, 4, 5, 6]], dtype=int32)

In [100]:
tf.reshape(m,(3,2)).eval()

array([[1, 2],
       [3, 4],
       [5, 6]], dtype=int32)

In [195]:
a = tf.constant([[1, 2], [3, 4]])
b = tf.constant([[5, 0], [0, 6]])
tf.accumulate_n([a, b, a]).eval()  # [[7, 4], [6, 14]]

array([[ 7,  4],
       [ 6, 14]], dtype=int32)

In [196]:
tf.add_n([a, b, a]).eval()

array([[ 7,  4],
       [ 6, 14]], dtype=int32)

In [202]:
tf.argmax(tf.constant([1,3,2,4,0])).eval()

3

In [203]:
tf.argmin(tf.constant([1,3,2,4,0])).eval()

4

In [ ]:
x = tf.constant([10.0, -1.0])
y = tf.map_fn(lambda m: tf.cond(tf.greater_equal(m, 0.0), 
                                true_fn = lambda: tf.constant(1.), 
                                false_fn = lambda : tf.constant(0.0)),
              x)

with tf.Session() as sess:
    print(sess.run(y))

In [ ]:
x = tf.constant([[10.0], [-1.0]])
y = tf.map_fn(lambda m: tf.cond(tf.greater_equal(m[0], 0.0), 
                                true_fn = lambda: tf.constant([1.]), 
                                false_fn = lambda : tf.constant([0.0])),
              x)

with tf.Session() as sess:
    print(sess.run(y))
    

### Variables y Placeholders

Las variables pueden entenderse como las variables locales de una función, las cuales no pueden ser accesadas desde el exterior de la función. Los placeholders son equivalentes a los parámetros, los cuales pueden tomar cualquier valor cuando se llama la función. En el siguiente ejemplo se evalua la expresión a * b - (b + c) para diferentes valores de a, b y c.

     [-] (node6)
      +--- [*] (node4)
      |     +---- [a] (node1)
      |     +---------------------+
      |                           |
      +--- [+] (node5)           [b] (node2)
            +---- [c] (node3)     |
            +---------------------+ 

In [106]:
a = tf.placeholder(tf.float32)
b = tf.placeholder(tf.float32)
c = tf.placeholder(tf.float32)
node4 = tf.multiply(a, b)
node5 = tf.add(c, b)
node6 = tf.subtract(node4, node5)

with tf.Session() as sess:
    print(sess.run(node6, feed_dict={a: 5, b:3, c:2}))
    print(sess.run(node6, feed_dict={a: 4, b:2, c:3}))
    print(sess.run(node6, feed_dict={a: 4, b:3, c:1}))

10.0
3.0
8.0


In [112]:
##
## la misma operación pero matricial
##
a = tf.placeholder(tf.float32, shape=(3,3))
b = tf.placeholder(tf.float32, shape=(3,3))
c = tf.placeholder(tf.float32, shape=(3,3))
node4 = tf.multiply(a, b)
node5 = tf.add(c, b)
node6 = tf.subtract(node4, node5)

with tf.Session() as sess:    
    print(sess.run(node6, feed_dict={a: [[1, 0, 0,],
                                         [0, 1, 0,],
                                         [0, 0, 1,]],
                                     b: np.random.normal(size=(3,3)), 
                                     c: np.random.normal(size=(3,3))}))

[[-0.86952245 -1.6432121   0.36080855]
 [ 0.54330117  1.1873457   1.4565654 ]
 [-0.21034712  0.40171003 -0.35921657]]


El siguiente ejemplo presente un acumulador para el calculo de $n = n + 1$.

    [=] (node1)  
     +---[n]
     +---[+] (node0)
          +----[n]
          +----[1]
     

In [113]:
## crea la variable y la inicializa a cero
n = tf.Variable(0)

## arbol sintactico que representa las operaciones
node0 = tf.add(n, tf.constant(1))
node1 = tf.assign(n, node0)

## evalua
with tf.Session() as sess:
    
    ## las variables deben ser inicializadas antes
    ## de usarse
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        ## el valor de las variables se retiene entre
        ## las llamadas a run()
        print(sess.run(node1))

1
2
3
4
5


In [204]:
## crea la variable y la inicializa a cero
n = tf.Variable(0)

## arbol sintactico que representa las operaciones
## se usa tf.assign_add para simplificar el arbol
## tambien existe tf.assign_sub
node0 = tf.assign_add(n, tf.constant(1))
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(5):
        print(sess.run(node0))

1
2
3
4
5


---
**Ejercicio.--** Indique para que sirven las siguientes funciones del modulo `tf` y realice un ejemplo:

    tf.clip_by_value
    tf.clip_by_norm
    tf.clip_by_average_norm
    tf.clip_by_global_norm
    tf.clip_by_norm
    tf.concat
    tf.case
    tf.cond
    tf.cumprod
    tf.cumsum
    tf.diag
    tf.inverse_permutation
    tf.log_sigmoid 
    tf.map_fn
    
    tf.matrix_inverse
    tf.matrix_diag
    tf.matrix_set_diag
    tf.matrix_solve
    tf.matrix_transpose
    tf.parallel_stack
    tf.stack
    tf.random_shuffle
    tf.reverse
    
    tf.maximum
    tf.minimum
    
---

In [118]:
W = tf.Variable([+0.3], dtype=tf.float32)
b = tf.Variable([-0.3], dtype=tf.float32)
x = tf.placeholder(tf.float32)
linear_model = W * x + b

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    print(sess.run(linear_model, feed_dict={x: [2.1]}))

[0.32999998]


### Funciones de activación

In [251]:
tf.nn.relu([-3., 3., 10.]).eval()

array([ 0.,  3., 10.], dtype=float32)

In [252]:
tf.nn.relu6([-3., 3., 10.]).eval()

array([0., 3., 6.], dtype=float32)

In [253]:
tf.nn.sigmoid([-1., 0., 1.]).eval()

array([0.26894143, 0.5       , 0.7310586 ], dtype=float32)

In [254]:
tf.nn.softsign([-1., 0., -1.]).eval()

array([-0.5,  0. , -0.5], dtype=float32)

In [255]:
tf.nn.softplus([-1., 0., -1.]).eval()

array([0.31326166, 0.6931472 , 0.31326166], dtype=float32)

In [256]:
tf.nn.elu([-1., 0., -1.]).eval()

array([-0.63212055,  0.        , -0.63212055], dtype=float32)

### Optimizacion de modelos (regresión lineal)

El siguiente ejemplo ilustra la construcción y estimación de un modelo de regresión lineal usando `TensorFlow`.

In [191]:
##
## Se generan 100 ejemplos para el modelo
##
##    y = w x + b + noise
##
## con w = [w1, ..., w_NDIM] 
##     b = 3.1, 
##     x ~ Normal(0, 1) 
##     noise ~ Normal(0,1) *  0.1
##
NDIM = 2
NSAMPLES = 100
b_real = np.random.randn()
w_real = np.random.randn(NDIM)
noise = 0.1 * np.random.randn(NSAMPLES, 1)
x_train = np.random.randn(NSAMPLES, NDIM)
y_train =  x_train @ w_real.reshape(NDIM, 1) + b_real + noise

In [193]:
##
## Define el modelo. 
##   w y b son los parámetros
##   x y y son variables (el modelo es generico)
##
w = tf.Variable([[0.1], [0.1]])
b = tf.Variable(0.1)
x = tf.placeholder(tf.float32, shape=(100, 2))
y = tf.placeholder(tf.float32, shape=(100, 1))

## Define el modelo
m = tf.add(tf.matmul(x, w), b)

## Define la función de error
sse = tf.reduce_sum(tf.square(m - y)) # sum of the squares

## Inicializa el optimizador
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.0001)
opt = optimizer.minimize(sse)



## estima el modelo
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(1000):
        sess.run(opt, {x:x_train, y:y_train})
        if (i % 200 == 0):
            print(sess.run(sse, {x:x_train, y:y_train}))
        
    print(sess.run([w, b], {x:x_train, y:y_train}))

print(w_real, b_real)    

43.49429
1.1256406
1.0881072
1.0880423
1.0880423
[array([[-0.5486508 ],
       [-0.06770671]], dtype=float32), 0.08353784]
[-0.55786119 -0.04897255] 0.08332631560763167


Introducción a TensorFlow 
===

**Juan David Velásquez Henao**  
jdvelasq@unal.edu.co   
Universidad Nacional de Colombia, Sede Medellín  
Facultad de Minas  
Medellín, Colombia

---

Haga click [aquí](https://github.com/jdvelasq/neural-networks/tree/master/) para acceder al repositorio online.

Haga click [aquí](http://nbviewer.jupyter.org/github/jdvelasq/neural-networks/tree/master/) para explorar el repositorio usando `nbviewer`. 